edge(a,c).
edge(c,a).
edge(a,b).
edge(b,a).
edge(c,d).
edge(d,c).
edge(b,d).
edge(d,b).

edge(aleksandrowlodzki, zgierz).
edge(annopol, krasnik).
edge(annopol, ozarow).
edge(antonin, olesnica).
edge(antonin, ostrowwielkopolski).
edge(augustow, elk).
edge(augustow, korycin).
edge(augustow, pomorze).
edge(augustow, raczki).
edge(babica, lutcza).
edge(babica, rzeszow).
edge(babieta, rucianenida).
edge(babieta, szczytno).
edge(baldram, jelen).
edge(balin, lodz).
edge(balin, uniejow).
edge(baranow, namyslow).
edge(bartoszyce, bezledy).
edge(bartoszyce, biskupiec).
edge(bartoszyce, lidzbarkwarminski).
edge(barwinek, dukla).
edge(bedzin, bytom).
edge(bedzin, sosnowiec).
edge(bedzin, wojkowicekoscielne).
edge(belchatow, piotrkowtrybunalski).
edge(belchatow, wielun).
edge(bezledy, bartoszyce).
edge(biala, bielsko).
edge(biala, kety).
edge(biala, zywiec).
edge(bialapiska, pisz).
edge(bialapiska, szczuczyn).
edge(bialeblota, pawlowek).
edge(bialeblota, wypaleniska).
edge(bialobrzegi, glowaczow).
edge(bialobrzegi, potworow).
edge(bialybor, bobolice).
edge(bialybor, czluchow).
edge(bialybor, miastko).
edge(bialybor, szczecinek).
edge(bialystok, bobrowniki).
edge(bialystok, korycin).
edge(bialystok, kuznica).
edge(bialystok, monki).
edge(bialystok, siemiatycze).
edge(bialystok, zambrow).
edge(biedrzychow, owczary).
edge(biedrzychow, strzelin).
edge(bielanywroclawskie, swidnica).
edge(bielsko, biala).
edge(bielsko, cieszyn).
edge(bielsko, tychy).
edge(bielskpodlaski, bransk).
edge(bielskpodlaski, kleszczele).
edge(bircza, kuzmina).
edge(bircza, przemysl).
edge(biskupiec, bartoszyce).
edge(biskupiec, szczytno).
edge(blachownia, czestochowa).
edge(blachownia, lubliniec).
edge(blaszki, kalisz).
edge(blaszki, sieradz).
edge(bobolice, bialybor).
edge(bobolice, koszalin).
edge(bobolice, szczecinek).
edge(boboszow, miedzylesie).
edge(bobrowniki, bialystok).
edge(boleslawiec, krzywa).
edge(boleslawiec, zgorzelec).
edge(bolkow, dobromierz).
edge(bolkow, jeleniagora).
edge(bolkow, kamiennagora).
edge(bolkow, legnica).
edge(braniewo, chrusciel).
edge(braniewo, gronowo).
edge(bransk, bielskpodlaski).
edge(bransk, wysokiemazowieckie).
edge(brodnica, lubawa).
edge(brodnica, torun).
edge(brzeg, namyslow).
edge(brzeg, opole).
edge(brzeg, owczary).
edge(brzeg, wroclaw).
edge(brzesckujawski, radziejow).
edge(brzesckujawski, wloclawek).
edge(brzesko, nowysacz).
edge(brzesko, targowisko).
edge(brzeziny, lodz).
edge(brzeziny, rawamazowiecka).
edge(budzisko, suwalki).
edge(busko, morawica).
edge(busko, zdroj).
edge(bydgoszcz, gniezno).
edge(bydgoszcz, inowroclaw).
edge(bydgoszcz, koronowo).
edge(bydgoszcz, oplawiec).
edge(bydgoszcz, pawlowek).
edge(bydgoszcz, swiecie).
edge(bydgoszcz, torun).
edge(bytom, bedzin).
edge(bytom, chorzow).
edge(bytom, gliwice).
edge(bytom, piekaryslaskie).
edge(bytom, pyskowice).
edge(bytom, tworog).
edge(bytow, koscierzyna).
edge(bytow, miastko).
edge(ceranow, sokolowpodlaski).
edge(ceranow, zambrow).
edge(chalupki, wodzislawslaski).
edge(chelm, dorohusk).
edge(chelm, piaski).
edge(chmielnik, jedrzejow).
edge(chociwel, stargardstargard).
edge(chociwel, wegorzyno).
edge(chodziez, oborniki).
edge(chodziez, ujscie).
edge(chojna, gryfino).
edge(chojna, krajnikdolny).
edge(chojna, mysliborz).
edge(chojna, sarbinowo).
edge(chojnice, czluchow).
edge(chojnice, starogardgdanski).
edge(chojnow, krzywa).
edge(chojnow, legnica).
edge(chorzow, bytom).
edge(chorzow, katowice).
edge(chrusciel, braniewo).
edge(chrusciel, elblag).
edge(chrusciel, grzechotki).
edge(chrzanow, jaworzno).
edge(chrzanow, katowice).
edge(chrzanow, krakow).
edge(chrzanow, trzebinia).
edge(chwaszczyno, zukowo).
edge(chyzne, rabkazdroj).
edge(ciechanow, glinojeck).
edge(ciechanow, makowmazowiecki).
edge(ciechanow, plonsk).
edge(cieszyn, bielsko).
edge(cycow, lublintatary).
edge(cycow, wlodawa).
edge(czaplinek, drawskopomorskie).
edge(czaplinek, szczecinek).
edge(czarlin, malbork).
edge(czarlin, starogardgdanski).
edge(czarnagora, jurgow).
edge(czarnagora, nowytarg).
edge(czeremcha, kleszczele).
edge(czeremcha, polowce).
edge(czestochowa, blachownia).
edge(czestochowa, janow).
edge(czestochowa, klobuck).
edge(czestochowa, klomnice).
edge(czestochowa, kozieglowy).
edge(czestochowa, piotrkowtrybunalski).
edge(czestochowa, pyrzowice).
edge(czluchow, bialybor).
edge(czluchow, chojnice).
edge(czluchow, sepolnokrajenskie).
edge(czluchow, walcz).
edge(dabrowagornicza, olkusz).
edge(dabrowagornicza, podwarpie).
edge(dabrowagornicza, sosnowiec).
edge(dabrowagornicza, tychy).
edge(dabrowatarnowska, szczucin).
edge(dabrowatarnowska, tarnow).
edge(darlowo, karwice).
edge(debica, rzeszow).
edge(debica, tarnow).
edge(deblin, kozienice).
edge(deblin, moszczanka).
edge(debno, mysliborz).
edge(debno, sarbinowo).
edge(dobra, sieradz).
edge(dobra, turek).
edge(dobremiasto, lidzbarkwarminski).
edge(dobremiasto, olsztyn).
edge(dobromierz, bolkow).
edge(dobromierz, kostomloty).
edge(dobromierz, swiebodzice).
edge(dobron, lublinek).
edge(dobron, roza).
edge(domaradz, lutcza).
edge(domaradz, miejscepiastowe).
edge(dorohusk, chelm).
edge(drawskopomorskie, czaplinek).
edge(drawskopomorskie, wegorzyno).
edge(drobin, glinojeck).
edge(drobin, plock).
edge(drobin, plonsk).
edge(drobin, sierpc).
edge(drohiczyn, siemiatycze).
edge(drohiczyn, sokolowpodlaski).
edge(drozow, glogow).
edge(drozow, radwanice).
edge(dukla, barwinek).
edge(dukla, miejscepiastowe).
edge(dzialoszyn, pajeczno).
edge(dzialoszyn, rudniki).
edge(elblag, chrusciel).
edge(elblag, gdansk).
edge(elblag, ostroda).
edge(elblag, starepole).
edge(elk, augustow).
edge(elk, grajewo).
edge(elk, mragowo).
edge(elk, olecko).
edge(elk, raczki).
edge(elk, szczuczyn).
edge(frampol, gorajec).
edge(frampol, janowlubelski).
edge(garwolin, ryki).
edge(garwolin, stoczeklukowski).
edge(garwolin, warszawa).
edge(garwolin, wilga).
edge(gdansk, elblag).
edge(gdansk, gdynia).
edge(gdansk, straszyn).
edge(gdansk, zukowo).
edge(gdanskport, tczew).
edge(gdynia, gdansk).
edge(gdynia, szemud).
edge(gdynia, zukowo).
edge(gizycko, pisz).
edge(gizycko, ryn).
edge(gizycko, wegorzewo).
edge(glinojeck, ciechanow).
edge(glinojeck, drobin).
edge(gliwice, bytom).
edge(gliwice, katowice).
edge(gliwice, mikolow).
edge(gliwice, nogowczyce).
edge(gliwice, rybnik).
edge(gliwice, tarnowskiegory).
edge(gliwice, wezelkleszczow).
edge(gliwice, zory).
edge(glogoczow, krakow).
edge(glogoczow, wadowice).
edge(glogow, drozow).
edge(glogow, szlichtyngowa).
edge(glogowmalopolski, kolbuszowa).
edge(glogowmalopolski, rzeszow).
edge(glowaczow, bialobrzegi).
edge(glowaczow, kozienice).
edge(glubczyce, pietrowice).
edge(glubczyce, renskawies).
edge(glucholazy, prudnik).
edge(gniezno, bydgoszcz).
edge(gniezno, poznan).
edge(gniezno, trzemeszno).
edge(gniezno, wrzesnia).
edge(goldap, olecko).
edge(goleniow, gorzowwielkopolski).
edge(goleniow, ploty).
edge(goleniow, szczecin).
edge(golina, konin).
edge(golina, slupca).
edge(golinsk, mieroszow).
edge(golnice, krzyzowa).
edge(golnice, olszyna).
edge(gorajec, frampol).
edge(gorajec, szczebrzeszyn).
edge(gorakalwaria, kozienice).
edge(gorakalwaria, warszawa).
edge(gorakalwariakolbiel, grojec).
edge(gorakalwariakolbiel, minskmazowiecki).
edge(gorlice, jaslo).
edge(gorlice, nowysacz).
edge(gorzowwielkopolski, goleniow).
edge(gorzowwielkopolski, walcz).
edge(gorzowwielkopolski, waldowice).
edge(gorzowwielkopolski, zielonagora).
edge(gorzyczki, zory).
edge(gorzyn, pniewy).
edge(gorzyn, skwierzyna).
edge(gostyn, jarocin).
edge(gostyn, leszno).
edge(gostynin, kutno).
edge(gostynin, plock).
edge(grajewo, elk).
edge(grajewo, monki).
edge(grojec, gorakalwariakolbiel).
edge(grojec, janki).
edge(grojec, mszczonow).
edge(grojec, radom).
edge(gronowo, braniewo).
edge(grudziadz, ilawa).
edge(grudziadz, kwidzyn).
edge(grudziadz, pruszczgdanski).
edge(grudziadz, stolno).
edge(grudziadz, torun).
edge(gryfino, chojna).
edge(gryfino, szczecin).
edge(gryfowslaski, luban).
edge(gryfowslaski, pasiecznik).
edge(grzechotki, chrusciel).
edge(gubinek, polupin).
edge(hrebenne, tomaszowlubelski).
edge(hrubieszow, zamosc).
edge(hrubieszow, zosin).
edge(hutazawadzka, skierniewice).
edge(ilawa, grudziadz).
edge(ilawa, wirwajdy).
edge(ilza, ostrowiecswietokrzyski).
edge(ilza, radom).
edge(inowlodz, potworow).
edge(inowlodz, tomaszowmazowiecki).
edge(inowroclaw, bydgoszcz).
edge(inowroclaw, strzelno).
edge(inowroclaw, torun).
edge(jablonna, legionowo).
edge(jablonna, warszawa).
edge(jakuszyce, jeleniagora).
edge(janki, grojec).
edge(janki, warszawa).
edge(janow, czestochowa).
edge(janow, szczekociny).
edge(janowlubelski, frampol).
edge(janowlubelski, krasnik).
edge(janowlubelski, nisko).
edge(jarocin, gostyn).
edge(jarocin, kornik).
edge(jarocin, krotoszyn).
edge(jarocin, miaskowo).
edge(jarocin, pleszew).
edge(jaroslaw, radymno).
edge(jaroslaw, rzeszow).
edge(jaroslaw, tryncza).
edge(jaslo, gorlice).
edge(jaslo, krosno).
edge(jaslo, pilzno).
edge(jaworzno, chrzanow).
edge(jaworzno, katowice).
edge(jedrzejow, chmielnik).
edge(jedrzejow, naglowice).
edge(jedrzychowice, zgorzelec).
edge(jedwabno, szczytno).
edge(jedwabno, zgnilocha).
edge(jelen, baldram).
edge(jeleniagora, bolkow).
edge(jeleniagora, jakuszyce).
edge(jeleniagora, pasiecznik).
edge(jezewostare, wizna).
edge(jurgow, czarnagora).
edge(kalisz, blaszki).
edge(kalisz, konin).
edge(kalisz, ostrowwielkopolski).
edge(kalisz, pleszew).
edge(kaluszyn, minskmazowiecki).
edge(kamiennagora, bolkow).
edge(kamiennagora, lubawka).
edge(kamiensk, piotrkowtrybunalski).
edge(kamiensk, radomsko).
edge(karwice, darlowo).
edge(karwice, koszalin).
edge(karwice, slupsk).
edge(katowice, chorzow).
edge(katowice, chrzanow).
edge(katowice, gliwice).
edge(katowice, jaworzno).
edge(katowice, mikolow).
edge(katowice, sosnowiec).
edge(katowice, tychy).
edge(kazun, nowydwormazowiecki).
edge(kedzierzyn, kozle).
edge(kedzierzyn, prudnik).
edge(kepno, kluczbork).
edge(kepno, ostrzeszow).
edge(kepno, sycow).
edge(kepno, zloczew).
edge(kety, biala).
edge(kety, wadowice).
edge(kielanowka, rzeszow).
edge(kielanowka, swilczaswilcza).
edge(kielce, krakow).
edge(kielce, lagow).
edge(kielce, morawica).
edge(kielce, radom).
edge(kielce, rudamaleniecka).
edge(kielce, wisniowka).
edge(kisielnica, lomza).
edge(kisielnica, pisz).
edge(kleszczele, bielskpodlaski).
edge(kleszczele, czeremcha).
edge(klimontow, lipnik).
edge(klimontow, loniow).
edge(klobuck, czestochowa).
edge(klobuck, rudniki).
edge(klodzko, miedzylesie).
edge(klodzko, nysa).
edge(klodzko, zabkowiceslaskie).
edge(klodzko, zdroj).
edge(klomnice, czestochowa).
edge(klomnice, radomsko).
edge(kluczbork, kepno).
edge(kluczbork, lubliniec).
edge(kluczbork, namyslow).
edge(kluczbork, opole).
edge(kluczbork, praszka).
edge(kobylniki, radziejow).
edge(kobylniki, strzelno).
edge(kock, lubartow).
edge(kock, miedzyrzecpodlaski).
edge(kock, moszczanka).
edge(kolbaskowo, szczecin).
edge(kolbuszowa, glogowmalopolski).
edge(kolbuszowa, nagnajow).
edge(kolobrzeg, koszalin).
edge(kolobrzeg, ploty).
edge(konin, golina).
edge(konin, kalisz).
edge(konin, kutno).
edge(konin, lodz).
edge(konin, poznan).
edge(konin, slesin).
edge(konin, turek).
edge(konskie, rudamaleniecka).
edge(konskie, skarzyskokamienna).
edge(korczowa, radymno).
edge(kornik, jarocin).
edge(kornik, poznan).
edge(koronowo, bydgoszcz).
edge(koronowo, sepolnokrajenskie).
edge(koronowo, trzeciewiec).
edge(korycin, augustow).
edge(korycin, bialystok).
edge(koscierzyna, bytow).
edge(koscierzyna, zukowo).
edge(kostomloty, dobromierz).
edge(kostomloty, wroclaw).
edge(kostrzyn, sarbinowo).
edge(kostrzyn, slubice).
edge(kostrzyn, waldowice).
edge(koszalin, bobolice).
edge(koszalin, karwice).
edge(koszalin, kolobrzeg).
edge(kowal, krosniewice).
edge(kowal, wloclawek).
edge(kozieglowy, czestochowa).
edge(kozienice, deblin).
edge(kozienice, glowaczow).
edge(kozienice, gorakalwaria).
edge(kozienice, zwolen).
edge(kozle, kedzierzyn).
edge(kozle, pyskowice).
edge(krajnikdolny, chojna).
edge(krakow, chrzanow).
edge(krakow, glogoczow).
edge(krakow, kielce).
edge(krakow, modlniczka).
edge(krakow, myslenice).
edge(krakow, niepolomice).
edge(krakow, nowahuta).
edge(krakow, nowebrzesko).
edge(krakow, skawina).
edge(krakow, tarnow).
edge(krakow, trzebinia).
edge(krakow, wieliczka).
edge(krapkowice, opole).
edge(krapkowice, raciborz).
edge(krasnik, annopol).
edge(krasnik, janowlubelski).
edge(krasnik, lublin).
edge(krasnystaw, piaski).
edge(krasnystaw, zamosc).
edge(kroscienko, ustrzykidolne).
edge(krosniewice, kowal).
edge(krosniewice, lodz).
edge(krosno, jaslo).
edge(krosno, sanok).
edge(krosnoodrzanskie, slubice).
edge(krotoszyn, jarocin).
edge(krotoszyn, milicz).
edge(krotoszyn, ostrowwielkopolski).
edge(krotoszyn, rawicz).
edge(krzywa, boleslawiec).
edge(krzywa, chojnow).
edge(krzyzanowice, raciborz).
edge(krzyzanowice, zabelkow).
edge(krzyzowa, golnice).
edge(krzyzowa, wroclaw).
edge(krzyzowa, zgorzelec).
edge(krzyzowka, nowysacz).
edge(krzyzowka, tylicz).
edge(kudowa, zdroj).
edge(kukuryki, wolkadobrynskaj).
edge(kurow, lublin).
edge(kurow, pulawy).
edge(kurow, ryki).
edge(kutno, gostynin).
edge(kutno, konin).
edge(kutno, lowicz).
edge(kutno, topolakrolewska).
edge(kuzmina, bircza).
edge(kuzmina, sanok).
edge(kuznica, bialystok).
edge(kwidzyn, grudziadz).
edge(kwidzyn, malbork).
edge(lagiewniki, strzelin).
edge(lagow, kielce).
edge(lagow, opatow).
edge(laliki, zwardon).
edge(laliki, zywiec).
edge(lask, rzgow).
edge(lask, sieradz).
edge(lebork, slupsk).
edge(lebork, szemud).
edge(legionowo, jablonna).
edge(legionowo, serock).
edge(legnica, bolkow).
edge(legnica, chojnow).
edge(legnica, lubin).
edge(legnica, prochowice).
edge(legowo, straszyn).
edge(leknica, zary).
edge(lesko, sanok).
edge(lesko, ustrzykidolne).
edge(leszno, gostyn).
edge(leszno, poznan).
edge(leszno, wroclaw).
edge(leszno, wschowa).
edge(lesznowola, warszawa).
edge(lezajsk, stalowawola).
edge(lezajsk, tryncza).
edge(lidzbarkwarminski, bartoszyce).
edge(lidzbarkwarminski, dobremiasto).
edge(limanowa, nowysacz).
edge(limanowa, rabkazdroj).
edge(lipnik, klimontow).
edge(lipnik, opatow).
edge(lipnik, sandomierz).
edge(lipno, sierpc).
edge(lipno, torun).
edge(lipno, wloclawek).
edge(lochow, minskmazowiecki).
edge(lochow, ostrowmazowiecka).
edge(lochow, wegrow).
edge(lochow, wyszkow).
edge(lodz, balin).
edge(lodz, brzeziny).
edge(lodz, konin).
edge(lodz, krosniewice).
edge(lodz, lublinek).
edge(lodz, piotrkowtrybunalski).
edge(lodz, sieradz).
edge(lodz, strykow).
edge(lodz, warszawa).
edge(lodz, wloclawek).
edge(lomza, kisielnica).
edge(lomza, ostroleka).
edge(lomza, piatnicapoduchowna).
edge(lomza, sniadowo).
edge(lomza, szczuczyn).
edge(lomza, zambrow).
edge(loniow, klimontow).
edge(loniow, nagnajow).
edge(lowicz, kutno).
edge(lowicz, skierniewice).
edge(lowicz, sochaczew).
edge(lowicz, strykow).
edge(luban, gryfowslaski).
edge(luban, zgorzelec).
edge(lubartow, kock).
edge(lubartow, lublin).
edge(lubawa, brodnica).
edge(lubawa, ostroda).
edge(lubawka, kamiennagora).
edge(lubicz, torun).
edge(lubieszyn, szczecin).
edge(lubin, legnica).
edge(lubin, prochowice).
edge(lubin, scinawa).
edge(lubin, zielonagora).
edge(lublin, krasnik).
edge(lublin, kurow).
edge(lublin, lubartow).
edge(lublin, piaski).
edge(lublinek, dobron).
edge(lublinek, lodz).
edge(lubliniec, blachownia).
edge(lubliniec, kluczbork).
edge(lubliniec, ozimek).
edge(lubliniec, tworog).
edge(lublintatary, cycow).
edge(lukow, radzynpodlaski).
edge(lukow, siedlce).
edge(lukow, stoczeklukowski).
edge(lutcza, babica).
edge(lutcza, domaradz).
edge(makowmazowiecki, ciechanow).
edge(makowmazowiecki, przasnysz).
edge(makowmazowiecki, pultusk).
edge(makowmazowiecki, rozan).
edge(malbork, czarlin).
edge(malbork, kwidzyn).
edge(malbork, starepole).
edge(medyka, przemysl).
edge(miaskowo, jarocin).
edge(miaskowo, miloslaw).
edge(miastko, bialybor).
edge(miastko, bytow).
edge(miastko, suchorze).
edge(miedzylesie, boboszow).
edge(miedzylesie, klodzko).
edge(miedzyrzecpodlaski, kock).
edge(miedzyrzecpodlaski, siemiatycze).
edge(miejscepiastowe, domaradz).
edge(miejscepiastowe, dukla).
edge(mieroszow, golinsk).
edge(mieroszow, walbrzych).
edge(mikolow, gliwice).
edge(mikolow, katowice).
edge(mikolow, tychy).
edge(mikolow, zory).
edge(milicz, krotoszyn).
edge(milicz, trzebnica).
edge(miloslaw, miaskowo).
edge(miloslaw, wrzesnia).
edge(minskmazowiecki, gorakalwariakolbiel).
edge(minskmazowiecki, kaluszyn).
edge(minskmazowiecki, lochow).
edge(minskmazowiecki, siedlce).
edge(minskmazowiecki, warszawa).
edge(minskmazowiecki, zakret).
edge(modlniczka, krakow).
edge(modlniczka, olkusz).
edge(monki, bialystok).
edge(monki, grajewo).
edge(morawica, busko).
edge(morawica, kielce).
edge(moszczanka, deblin).
edge(moszczanka, kock).
edge(mragowo, elk).
edge(mragowo, nawiady).
edge(mragowo, olsztyn).
edge(mragowo, ryn).
edge(mszczonow, grojec).
edge(mszczonow, sochaczew).
edge(muszynka, tylicz).
edge(myslenice, krakow).
edge(myslenice, rabkazdroj).
edge(mysliborz, chojna).
edge(mysliborz, debno).
edge(mysliborz, mysliborz).
edge(myszyniec, ostroleka).
edge(myszyniec, rozogi).
edge(naglowice, jedrzejow).
edge(naglowice, szczekociny).
edge(nagnajow, kolbuszowa).
edge(nagnajow, loniow).
edge(namyslow, baranow).
edge(namyslow, brzeg).
edge(namyslow, kluczbork).
edge(nawiady, mragowo).
edge(nawiady, rozogi).
edge(niepolomice, krakow).
edge(niepolomice, targowisko).
edge(nisko, janowlubelski).
edge(nisko, sokolowmalopolski).
edge(nogowczyce, gliwice).
edge(nogowczyce, prady).
edge(nowabrzeznica, pajeczno).
edge(nowabrzeznica, radomsko).
edge(nowahuta, krakow).
edge(nowebrzesko, krakow).
edge(nowebrzesko, polaniec).
edge(nowemarzy, swiecie).
edge(nowyduninow, plock).
edge(nowyduninow, wloclawek).
edge(nowydwormazowiecki, kazun).
edge(nowydwormazowiecki, pomiechowek).
edge(nowydwormazowiecki, wyszogrod).
edge(nowysacz, brzesko).
edge(nowysacz, gorlice).
edge(nowysacz, krzyzowka).
edge(nowysacz, limanowa).
edge(nowysacz, starysacz).
edge(nowytarg, czarnagora).
edge(nowytarg, rabkazdroj).
edge(nowytarg, zakopane).
edge(nysa, klodzko).
edge(nysa, opole).
edge(nysa, prudnik).
edge(oborniki, chodziez).
edge(oborniki, poznan).
edge(ogrodniki, pockuny).
edge(olecko, elk).
edge(olecko, goldap).
edge(olesnica, antonin).
edge(olesnica, sycow).
edge(olesnica, wroclaw).
edge(olkusz, dabrowagornicza).
edge(olkusz, modlniczka).
edge(olsztyn, dobremiasto).
edge(olsztyn, mragowo).
edge(olsztyn, olsztynek).
edge(olsztyn, ostroda).
edge(olsztyn, szczytno).
edge(olsztynek, olsztyn).
edge(olsztynek, ostroda).
edge(olsztynek, plonsk).
edge(olsztynek, zgnilocha).
edge(olszyna, golnice).
edge(opatow, lagow).
edge(opatow, lipnik).
edge(opatow, ostrowiecswietokrzyski).
edge(opatow, ozarow).
edge(oplawiec, bydgoszcz).
edge(opoczno, przysucha).
edge(opoczno, sulejow).
edge(opole, brzeg).
edge(opole, kluczbork).
edge(opole, krapkowice).
edge(opole, nysa).
edge(opole, ozimek).
edge(opole, strzelceopolskie).
edge(ostroda, elblag).
edge(ostroda, lubawa).
edge(ostroda, olsztyn).
edge(ostroda, olsztynek).
edge(ostroda, wirwajdy).
edge(ostroleka, lomza).
edge(ostroleka, myszyniec).
edge(ostroleka, rozan).
edge(ostrowiecswietokrzyski, ilza).
edge(ostrowiecswietokrzyski, opatow).
edge(ostrowmazowiecka, lochow).
edge(ostrowmazowiecka, rozan).
edge(ostrowmazowiecka, wyszkow).
edge(ostrowmazowiecka, zambrow).
edge(ostrowwielkopolski, antonin).
edge(ostrowwielkopolski, kalisz).
edge(ostrowwielkopolski, krotoszyn).
edge(ostrowwielkopolski, ostrzeszow).
edge(ostrowwielkopolski, pleszew).
edge(ostrzeszow, kepno).
edge(ostrzeszow, ostrowwielkopolski).
edge(oswiecim, tychy).
edge(oswiecim, zator).
edge(owczary, biedrzychow).
edge(owczary, brzeg).
edge(ozarow, annopol).
edge(ozarow, opatow).
edge(ozimek, lubliniec).
edge(ozimek, opole).
edge(pajeczno, dzialoszyn).
edge(pajeczno, nowabrzeznica).
edge(pasiecznik, gryfowslaski).
edge(pasiecznik, jeleniagora).
edge(pawlowek, bialeblota).
edge(pawlowek, bydgoszcz).
edge(pawlowek, pila).
edge(piaski, chelm).
edge(piaski, krasnystaw).
edge(piaski, lublin).
edge(piatnicapoduchowna, lomza).
edge(piatnicapoduchowna, wizna).
edge(piekaryslaskie, bytom).
edge(piekaryslaskie, pyrzowice).
edge(pietrowice, glubczyce).
edge(pila, pawlowek).
edge(pila, podgaje).
edge(pila, ujscie).
edge(pila, walcz).
edge(pilzno, jaslo).
edge(pilzno, tarnow).
edge(piotrkowtrybunalski, belchatow).
edge(piotrkowtrybunalski, czestochowa).
edge(piotrkowtrybunalski, kamiensk).
edge(piotrkowtrybunalski, lodz).
edge(piotrkowtrybunalski, rawamazowiecka).
edge(piotrkowtrybunalski, rzgow).
edge(piotrkowtrybunalski, sulejow).
edge(pisz, bialapiska).
edge(pisz, gizycko).
edge(pisz, kisielnica).
edge(pisz, rucianenida).
edge(piwnicznazdroj, starysacz).
edge(pleszew, jarocin).
edge(pleszew, kalisz).
edge(pleszew, ostrowwielkopolski).
edge(plock, drobin).
edge(plock, gostynin).
edge(plock, nowyduninow).
edge(plock, wyszogrod).
edge(plonsk, ciechanow).
edge(plonsk, drobin).
edge(plonsk, olsztynek).
edge(plonsk, warszawa).
edge(plonsk, wyszogrod).
edge(ploty, goleniow).
edge(ploty, kolobrzeg).
edge(pniewy, gorzyn).
edge(pniewy, poznan).
edge(pniewy, swiebodzin).
edge(pockuny, ogrodniki).
edge(pockuny, pomorze).
edge(podgaje, pila).
edge(podgaje, szczecinek).
edge(podwarpie, dabrowagornicza).
edge(podwarpie, pyrzowice).
edge(podwarpie, siewierz).
edge(podwarpiepodwarpie, wojkowicekoscielne).
edge(polaniec, nowebrzesko).
edge(polaniec, sandomierz).
edge(polowce, czeremcha).
edge(polupin, gubinek).
edge(polupin, zielonagora).
edge(pomiechowek, nowydwormazowiecki).
edge(pomiechowek, serock).
edge(pomorze, augustow).
edge(pomorze, pockuny).
edge(potworow, bialobrzegi).
edge(potworow, inowlodz).
edge(poznan, gniezno).
edge(poznan, konin).
edge(poznan, kornik).
edge(poznan, leszno).
edge(poznan, oborniki).
edge(poznan, pniewy).
edge(poznan, rzepin).
edge(poznan, wrzesnia).
edge(prady, nogowczyce).
edge(prady, wroclaw).
edge(praszka, kluczbork).
edge(praszka, rudniki).
edge(praszka, wielun).
edge(prochowice, legnica).
edge(prochowice, lubin).
edge(prochowice, wroclaw).
edge(prudnik, glucholazy).
edge(prudnik, kedzierzyn).
edge(prudnik, nysa).
edge(prudnik, trzebina).
edge(pruszczgdanski, grudziadz).
edge(przasnysz, makowmazowiecki).
edge(przasnysz, szczytno).
edge(przeclaw, rosowek).
edge(przeclaw, szczecin).
edge(przedborz, radomsko).
edge(przedborz, rudamaleniecka).
edge(przemkow, radwanice).
edge(przemkow, szprotawa).
edge(przemysl, bircza).
edge(przemysl, medyka).
edge(przemysl, radymno).
edge(przewoz, zary).
edge(przylubie, torun).
edge(przylubie, wypaleniska).
edge(przysucha, opoczno).
edge(przysucha, radom).
edge(pulawy, kurow).
edge(pulawy, zwolen).
edge(pultusk, makowmazowiecki).
edge(pyrzowice, czestochowa).
edge(pyrzowice, piekaryslaskie).
edge(pyrzowice, podwarpie).
edge(pyskowice, bytom).
edge(pyskowice, kozle).
edge(pyskowice, toszek).
edge(rabkazdroj, chyzne).
edge(rabkazdroj, limanowa).
edge(rabkazdroj, myslenice).
edge(rabkazdroj, nowytarg).
edge(rabkazdroj, wadowice).
edge(rabkazdroj, zabornia).
edge(raciborz, krapkowice).
edge(raciborz, krzyzanowice).
edge(raczki, augustow).
edge(raczki, elk).
edge(raczki, suwalki).
edge(radom, grojec).
edge(radom, ilza).
edge(radom, kielce).
edge(radom, przysucha).
edge(radom, zwolen).
edge(radomsko, kamiensk).
edge(radomsko, klomnice).
edge(radomsko, nowabrzeznica).
edge(radomsko, przedborz).
edge(radwanice, drozow).
edge(radwanice, przemkow).
edge(radymno, jaroslaw).
edge(radymno, korczowa).
edge(radymno, przemysl).
edge(radziejow, brzesckujawski).
edge(radziejow, kobylniki).
edge(radzymin, warszawa).
edge(radzymin, wyszkow).
edge(radzynpodlaski, lukow).
edge(radzynpodlaski, wisznice).
edge(rawamazowiecka, brzeziny).
edge(rawamazowiecka, piotrkowtrybunalski).
edge(rawamazowiecka, warszawa).
edge(rawicz, krotoszyn).
edge(rawicz, zalecze).
edge(renskawies, glubczyce).
edge(rosowek, przeclaw).
edge(roza, dobron).
edge(rozan, makowmazowiecki).
edge(rozan, ostroleka).
edge(rozan, ostrowmazowiecka).
edge(rozan, serock).
edge(rozogi, myszyniec).
edge(rozogi, nawiady).
edge(rozogi, szczytno).
edge(rucianenida, babieta).
edge(rucianenida, pisz).
edge(rudamaleniecka, kielce).
edge(rudamaleniecka, konskie).
edge(rudamaleniecka, przedborz).
edge(rudamaleniecka, zarnow).
edge(rudnik, skarzyskokamienna).
edge(rudniki, dzialoszyn).
edge(rudniki, klobuck).
edge(rudniki, praszka).
edge(rudniki, wielun).
edge(rybnik, gliwice).
edge(rybnik, wodzislawslaski).
edge(ryki, garwolin).
edge(ryki, kurow).
edge(ryn, gizycko).
edge(ryn, mragowo).
edge(rzepin, poznan).
edge(rzepin, swiebodzin).
edge(rzepin, swiecko).
edge(rzeszow, babica).
edge(rzeszow, debica).
edge(rzeszow, glogowmalopolski).
edge(rzeszow, jaroslaw).
edge(rzeszow, kielanowka).
edge(rzeszow, sokolowmalopolski).
edge(rzeszow, tarnow).
edge(rzgow, lask).
edge(rzgow, piotrkowtrybunalski).
edge(sandomierz, lipnik).
edge(sandomierz, polaniec).
edge(sandomierz, stalowawola).
edge(sandomierz, zwolen).
edge(sanok, krosno).
edge(sanok, kuzmina).
edge(sanok, lesko).
edge(sarbinowo, chojna).
edge(sarbinowo, debno).
edge(sarbinowo, kostrzyn).
edge(scinawa, lubin).
edge(scinawa, winsko).
edge(sepolnokrajenskie, czluchow).
edge(sepolnokrajenskie, koronowo).
edge(serock, legionowo).
edge(serock, pomiechowek).
edge(serock, rozan).
edge(serock, wierzbica).
edge(siedlce, lukow).
edge(siedlce, minskmazowiecki).
edge(siedlce, sokolowpodlaski).
edge(siedlce, terespol).
edge(siemiatycze, bialystok).
edge(siemiatycze, drohiczyn).
edge(siemiatycze, miedzyrzecpodlaski).
edge(sieradz, blaszki).
edge(sieradz, dobra).
edge(sieradz, lask).
edge(sieradz, lodz).
edge(sieradz, zloczew).
edge(sierpc, drobin).
edge(sierpc, lipno).
edge(siewierz, podwarpie).
edge(siewierz, swierklaniec).
edge(siewierz, zawiercie).
edge(skarzyskokamienna, konskie).
edge(skarzyskokamienna, rudnik).
edge(skawina, krakow).
edge(skawina, zator).
edge(skierniewice, hutazawadzka).
edge(skierniewice, lowicz).
edge(skoczow, zory).
edge(skwierzyna, gorzyn).
edge(skwierzyna, waldowice).
edge(slawatycze, wisznice).
edge(slesin, konin).
edge(slesin, strzelno).
edge(slubice, kostrzyn).
edge(slubice, krosnoodrzanskie).
edge(slupca, golina).
edge(slupca, wrzesnia).
edge(slupsk, karwice).
edge(slupsk, lebork).
edge(slupsk, suchorze).
edge(slupsk, ustka).
edge(sniadowo, lomza).
edge(sochaczew, lowicz).
edge(sochaczew, mszczonow).
edge(sochaczew, warszawa).
edge(sochaczew, wyszogrod).
edge(sokolowmalopolski, nisko).
edge(sokolowmalopolski, rzeszow).
edge(sokolowpodlaski, ceranow).
edge(sokolowpodlaski, drohiczyn).
edge(sokolowpodlaski, siedlce).
edge(sokolowpodlaski, wegrow).
edge(sosnowiec, bedzin).
edge(sosnowiec, dabrowagornicza).
edge(sosnowiec, katowice).
edge(stalowawola, lezajsk).
edge(stalowawola, sandomierz).
edge(starepole, elblag).
edge(starepole, malbork).
edge(stargard, szczecin).
edge(stargard, walcz).
edge(stargardstargard, chociwel).
edge(starogardgdanski, chojnice).
edge(starogardgdanski, czarlin).
edge(starysacz, nowysacz).
edge(starysacz, piwnicznazdroj).
edge(steszew, wolsztyn).
edge(stoczeklukowski, garwolin).
edge(stoczeklukowski, lukow).
edge(stolno, grudziadz).
edge(straszyn, gdansk).
edge(straszyn, legowo).
edge(strykow, lodz).
edge(strykow, lowicz).
edge(strykow, zgierz).
edge(strzelceopolskie, opole).
edge(strzelceopolskie, toszek).
edge(strzelceopolskie, wezelkleszczow).
edge(strzelin, biedrzychow).
edge(strzelin, lagiewniki).
edge(strzelno, inowroclaw).
edge(strzelno, kobylniki).
edge(strzelno, slesin).
edge(strzelno, wylatowo).
edge(suchorze, miastko).
edge(suchorze, slupsk).
edge(sulechow, wolsztyn).
edge(sulechow, zielonagora).
edge(sulejow, opoczno).
edge(sulejow, piotrkowtrybunalski).
edge(sulejow, zarnow).
edge(suwalki, budzisko).
edge(suwalki, raczki).
edge(swidnica, bielanywroclawskie).
edge(swidnica, swiebodzice).
edge(swiebodzice, dobromierz).
edge(swiebodzice, swidnica).
edge(swiebodzice, walbrzych).
edge(swiebodzin, pniewy).
edge(swiebodzin, rzepin).
edge(swiecie, bydgoszcz).
edge(swiecie, nowemarzy).
edge(swiecie, tczew).
edge(swiecie, torun).
edge(swiecko, rzepin).
edge(swierklaniec, siewierz).
edge(swierklaniec, tarnowskiegory).
edge(swilczaswilcza, kielanowka).
edge(swinoujscie, szczecin).
edge(sycow, kepno).
edge(sycow, olesnica).
edge(szczebrzeszyn, gorajec).
edge(szczebrzeszyn, zamosc).
edge(szczecin, goleniow).
edge(szczecin, gryfino).
edge(szczecin, kolbaskowo).
edge(szczecin, lubieszyn).
edge(szczecin, przeclaw).
edge(szczecin, stargard).
edge(szczecin, swinoujscie).
edge(szczecinek, bialybor).
edge(szczecinek, bobolice).
edge(szczecinek, czaplinek).
edge(szczecinek, podgaje).
edge(szczekociny, janow).
edge(szczekociny, naglowice).
edge(szczekociny, zawiercie).
edge(szczucin, dabrowatarnowska).
edge(szczucin, zdroj).
edge(szczuczyn, bialapiska).
edge(szczuczyn, elk).
edge(szczuczyn, lomza).
edge(szczytno, babieta).
edge(szczytno, biskupiec).
edge(szczytno, jedwabno).
edge(szczytno, olsztyn).
edge(szczytno, przasnysz).
edge(szczytno, rozogi).
edge(szemud, gdynia).
edge(szemud, lebork).
edge(szlichtyngowa, glogow).
edge(szlichtyngowa, wschowa).
edge(szprotawa, przemkow).
edge(szprotawa, zagan).
edge(tarczyn, tarczyn).
edge(targowisko, brzesko).
edge(targowisko, niepolomice).
edge(tarnow, dabrowatarnowska).
edge(tarnow, debica).
edge(tarnow, krakow).
edge(tarnow, pilzno).
edge(tarnow, rzeszow).
edge(tarnow, wieliczka).
edge(tarnowskiegory, gliwice).
edge(tarnowskiegory, swierklaniec).
edge(tczew, gdanskport).
edge(tczew, swiecie).
edge(terespol, siedlce).
edge(tomaszowlubelski, hrebenne).
edge(tomaszowlubelski, zamosc).
edge(tomaszowmazowiecki, inowlodz).
edge(topolakrolewska, kutno).
edge(torun, brodnica).
edge(torun, bydgoszcz).
edge(torun, grudziadz).
edge(torun, inowroclaw).
edge(torun, lipno).
edge(torun, lubicz).
edge(torun, przylubie).
edge(torun, swiecie).
edge(torun, wloclawek).
edge(toszek, pyskowice).
edge(toszek, strzelceopolskie).
edge(tryncza, jaroslaw).
edge(tryncza, lezajsk).
edge(trzebina, prudnik).
edge(trzebinia, chrzanow).
edge(trzebinia, krakow).
edge(trzebnica, milicz).
edge(trzeciewiec, koronowo).
edge(trzemeszno, gniezno).
edge(trzemeszno, wylatowo).
edge(turek, dobra).
edge(turek, konin).
edge(turek, uniejow).
edge(tworog, bytom).
edge(tworog, lubliniec).
edge(tychy, bielsko).
edge(tychy, dabrowagornicza).
edge(tychy, katowice).
edge(tychy, mikolow).
edge(tychy, oswiecim).
edge(tylicz, krzyzowka).
edge(tylicz, muszynka).
edge(ujscie, chodziez).
edge(ujscie, pila).
edge(uniejow, balin).
edge(uniejow, turek).
edge(ustka, slupsk).
edge(ustrzykidolne, kroscienko).
edge(ustrzykidolne, lesko).
edge(wadowice, glogoczow).
edge(wadowice, kety).
edge(wadowice, rabkazdroj).
edge(wadowice, zator).
edge(walbrzych, mieroszow).
edge(walbrzych, swiebodzice).
edge(walcz, czluchow).
edge(walcz, gorzowwielkopolski).
edge(walcz, pila).
edge(walcz, stargard).
edge(waldowice, gorzowwielkopolski).
edge(waldowice, kostrzyn).
edge(waldowice, skwierzyna).
edge(warszawa, garwolin).
edge(warszawa, gorakalwaria).
edge(warszawa, jablonna).
edge(warszawa, janki).
edge(warszawa, lesznowola).
edge(warszawa, lodz).
edge(warszawa, minskmazowiecki).
edge(warszawa, plonsk).
edge(warszawa, radzymin).
edge(warszawa, rawamazowiecka).
edge(warszawa, sochaczew).
edge(warszawa, zakret).
edge(wegorzewo, gizycko).
edge(wegorzyno, chociwel).
edge(wegorzyno, drawskopomorskie).
edge(wegrow, lochow).
edge(wegrow, sokolowpodlaski).
edge(wezelkleszczow, gliwice).
edge(wezelkleszczow, strzelceopolskie).
edge(wieliczka, krakow).
edge(wieliczka, tarnow).
edge(wielun, belchatow).
edge(wielun, praszka).
edge(wielun, rudniki).
edge(wielun, wielun).
edge(wielun, zloczew).
edge(wierzbica, serock).
edge(wierzbica, wyszkow).
edge(wilga, garwolin).
edge(winsko, scinawa).
edge(winsko, zalecze).
edge(wirwajdy, ilawa).
edge(wirwajdy, ostroda).
edge(wisniowka, kielce).
edge(wisznice, radzynpodlaski).
edge(wisznice, slawatycze).
edge(wizna, jezewostare).
edge(wizna, piatnicapoduchowna).
edge(wloclawek, brzesckujawski).
edge(wloclawek, kowal).
edge(wloclawek, lipno).
edge(wloclawek, lodz).
edge(wloclawek, nowyduninow).
edge(wloclawek, torun).
edge(wlodawa, cycow).
edge(wodzislawslaski, chalupki).
edge(wodzislawslaski, rybnik).
edge(wojkowicekoscielne, bedzin).
edge(wojkowicekoscielne, podwarpiepodwarpie).
edge(wolkadobrynskaj, kukuryki).
edge(wolsztyn, steszew).
edge(wolsztyn, sulechow).
edge(wroclaw, brzeg).
edge(wroclaw, kostomloty).
edge(wroclaw, krzyzowa).
edge(wroclaw, leszno).
edge(wroclaw, olesnica).
edge(wroclaw, prady).
edge(wroclaw, prochowice).
edge(wroclaw, zabkowiceslaskie).
edge(wrzesnia, gniezno).
edge(wrzesnia, miloslaw).
edge(wrzesnia, poznan).
edge(wrzesnia, slupca).
edge(wschowa, leszno).
edge(wschowa, szlichtyngowa).
edge(wylatowo, strzelno).
edge(wylatowo, trzemeszno).
edge(wypaleniska, bialeblota).
edge(wypaleniska, przylubie).
edge(wysokiemazowieckie, bransk).
edge(wysokiemazowieckie, zambrow).
edge(wyszkow, lochow).
edge(wyszkow, ostrowmazowiecka).
edge(wyszkow, radzymin).
edge(wyszkow, wierzbica).
edge(wyszogrod, nowydwormazowiecki).
edge(wyszogrod, plock).
edge(wyszogrod, plonsk).
edge(wyszogrod, sochaczew).
edge(zabelkow, krzyzanowice).
edge(zabkowiceslaskie, klodzko).
edge(zabkowiceslaskie, wroclaw).
edge(zabornia, rabkazdroj).
edge(zagan, szprotawa).
edge(zagan, zary).
edge(zakopane, nowytarg).
edge(zakret, minskmazowiecki).
edge(zakret, warszawa).
edge(zalecze, rawicz).
edge(zalecze, winsko).
edge(zambrow, bialystok).
edge(zambrow, ceranow).
edge(zambrow, lomza).
edge(zambrow, ostrowmazowiecka).
edge(zambrow, wysokiemazowieckie).
edge(zambrow, zambrow).
edge(zamosc, hrubieszow).
edge(zamosc, krasnystaw).
edge(zamosc, szczebrzeszyn).
edge(zamosc, tomaszowlubelski).
edge(zarnow, rudamaleniecka).
edge(zarnow, sulejow).
edge(zary, leknica).
edge(zary, przewoz).
edge(zary, zagan).
edge(zary, zielonagora).
edge(zator, oswiecim).
edge(zator, skawina).
edge(zator, wadowice).
edge(zawiercie, siewierz).
edge(zawiercie, szczekociny).
edge(zdroj, busko).
edge(zdroj, klodzko).
edge(zdroj, kudowa).
edge(zdroj, szczucin).
edge(zgierz, aleksandrowlodzki).
edge(zgierz, strykow).
edge(zgnilocha, jedwabno).
edge(zgnilocha, olsztynek).
edge(zgorzelec, boleslawiec).
edge(zgorzelec, jedrzychowice).
edge(zgorzelec, krzyzowa).
edge(zgorzelec, luban).
edge(zielonagora, gorzowwielkopolski).
edge(zielonagora, lubin).
edge(zielonagora, polupin).
edge(zielonagora, sulechow).
edge(zielonagora, zary).
edge(zloczew, kepno).
edge(zloczew, sieradz).
edge(zloczew, wielun).
edge(zory, gliwice).
edge(zory, gorzyczki).
edge(zory, mikolow).
edge(zory, skoczow).
edge(zosin, hrubieszow).
edge(zukowo, chwaszczyno).
edge(zukowo, gdansk).
edge(zukowo, gdynia).
edge(zukowo, koscierzyna).
edge(zwardon, laliki).
edge(zwolen, kozienice).
edge(zwolen, pulawy).
edge(zwolen, radom).
edge(zwolen, sandomierz).
edge(zywiec, biala).
edge(zywiec, laliki).
